DjangoQuiz/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from quizez import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quizez.urls', namespace="quizez")),
    path('', views.home, name='home'),
    path('results/', views.results, name='results'),

    # Auth
    path('signup/', views.signupUser, name='signupUser'),
    path('login/', views.loginUser, name='loginUser'),
    path('logout/', views.logoutUser, name='logoutUser'),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

quizez/urls.py
from django.urls import path

from .views import *

app_name = 'quizez'

urlpatterns = [

    # quiz
    path('main/', QuizListView.as_view(), name='main-view'),
    path('main/<pk>/', quiz_view, name='quiz-view'),
    path('main/<pk>/save/', save_quiz_view, name='save-view'),
    path('main/<pk>/data/', quiz_data_view, name='quiz-data-view'),


]

questions/models.py
from django.db import models
from quizez.models import *


class Question(models.Model):
    text = models.CharField(max_length=200)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.text)

    def get_answers(self):
        return self.answer_set.all()


class Answer(models.Model):
    text = models.CharField(max_length=200)
    correct = models.BooleanField(default=False)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"question: {self.question.text}, answer: {self.text}, correct: {self.correct}"

quizez/models.py
from django.db import models
import random
# Create your models here.


class Quiz(models.Model):
    name = models.CharField(max_length=200)
    topic = models.CharField(max_length=200)
    number_of_questions = models.IntegerField()
    required_score_to_pass = models.IntegerField(
        help_text="Required Score to pass")

    def __str__(self):
        return f"{self.name} - {self.topic}"

    def get_questions(self):
        questions = list(self.question_set.all())
        random.shuffle(questions)
        return questions[:self.number_of_questions]

    class Meta:
        verbose_name_plural = 'Quizes'

results/models.py
from django.db import models
from quizez.models import *
from django.contrib.auth.models import User


class Result(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    score = models.FloatField()

    def __str__(self):
        return str(self.pk)

questions/views.py
from django.shortcuts import render

# Create your views here.

quizez/views.py
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.db import IntegrityError
from django.http import JsonResponse
from django.shortcuts import render, redirect


# Create your views here.
from django.views.generic import ListView

from questions.models import Question, Answer
from quizez.models import Quiz
from results.models import Result


def home(request):
    return render(request, 'quizez/home.html')


def signupUser(request):
    if request.method == 'GET':
        return render(request, 'quizez/signupUser.html')
    else:
        if request.POST['password1'] == request.POST['password2']:
            try:
                user = User.objects.create_user(
                    request.POST['username'], password=request.POST['password1'])
                user.save()
                login(request, user)
                return redirect('/main')
            except IntegrityError:
                return render(request, 'quizez/signupUser.html', {'form': UserCreationForm(), 'error': 'Username has '
                                                                                                       'already '
                                                                                                       'exists. '
                                                                                                       'Please select '
                                                                                                       'new username'})
        else:
            return render(request, 'quizez/signupUser.html', {'form': UserCreationForm(), 'error': 'Passwords did not '
                                                                                                   'match'})


def loginUser(request):
    if request.method == 'GET':
        return render(request, 'quizez/loginUser.html', {'form': AuthenticationForm()})
    else:
        user = authenticate(
            request, username=request.POST['username'], password=request.POST['password'])
        if user is None:
            return render(request, 'quizez/loginUser.html', {'form': AuthenticationForm(), 'error': 'Username and '
                                                                                                    'password did not '
                                                                                                    'match'})
        else:
            login(request, user)
            return redirect('/main')


@login_required
def logoutUser(request):
    if request.method == 'POST':
        logout(request)
        return redirect('home')


class QuizListView(ListView):
    Model = Quiz
    template_name = 'quizez/main.html'
    context_object_name = "quiz"

    def get_queryset(self):
        return Quiz.objects.all()


@login_required
def quiz_view(request, pk):
    quiz = Quiz.objects.get(pk=pk)
    return render(request, 'quizez/quiz.html', {'obj': quiz})


@login_required
def quiz_data_view(request, pk):

    quiz = Quiz.objects.get(pk=pk)
    question = []

    for q in quiz.get_questions():
        answer = []
        for a in q.get_answers():
            answer.append(a.text)
        question.append({str(q): answer})
    return JsonResponse({
        'data': question,
    })


@login_required
def save_quiz_view(request, pk):
    print(request.POST)

    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        questions = []
        data = request.POST
        data_ = dict(data.lists())

        data_.pop('csrfmiddlewaretoken')

        for k in data_.keys():
            print("keys ", k)
            question = Question.objects.get(text=k)
            questions.append(question)
        print(questions)

        user = request.user
        quiz = Quiz.objects.get(pk=pk)
        score = 0
        multiplier = 100 / quiz.number_of_questions
        results = []
        correct_answer = None

        for q in questions:
            a_selected = request.POST.get(q.text)

            if a_selected != "":
                print(a_selected)
                questions_answers = Answer.objects.filter(question=q)

                for a in questions_answers:
                    if a_selected == a.text:
                        if a.correct:
                            score += 1
                            correct_answer = a.text
                    else:
                        if a.correct:
                            correct_answer = a.text
                results.append(
                    {str(q): {'correct_answer': correct_answer, 'answered': a_selected}})

            else:
                results.append({str(q): 'not answered'})
        final_res = score * multiplier
        print(final_res)
        Result.objects.create(quiz=quiz, user=user, score=final_res)
        if final_res > 40:
            return JsonResponse({'passed': True, 'score': final_res, 'results': results})
        else:
            return JsonResponse({'passed': False, 'score': final_res, 'results': results})


@login_required
def results(request):
    results = Result.objects.all()
    return render(request, "quizez/results.html", {'results': results})

results/views.py
from django.shortcuts import render

# Create your views here.

quizez/templates/quizez/home.html
{% extends "base.html" %}

{% block title %}

Python

{% endblock title %}

{% block content %}
<br>
<br>
<br>
<br>
<br>
<br>
<div class="row justify-content-center mt-5">
    <div class="col-md-7 text-center">

        <h1>Take Quiz using Django & Python.</h1>

        <br>
        <br>
        <a role="button" class="btn btn-primary btn-lg" href="/signup">Start</a>
    </div>

</div>
{% endblock %}

quizez/templates/quizez/loginuser.html
{% extends "base.html" %}

{% block content %}
<div class="row justify-content-center mt-5">
    <div class="col-md-5">
        <h2>Login</h2>
    </div>
</div>
<div class="row justify-content-center mt-5">
    <div class="col-md-5">
        {% if error %}
        <div class="alert alert-danger" role="alert">
            {{ error }}
        </div>
        {% endif %}
        <form method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="username">Username</label>
                <input type="text" name="username" class="form-control" id="username">
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" name="password" class="form-control" id="password">
            </div>
            <button type="submit" class="btn btn-primary">Login</button>
        </form>
        <hr>
        <div class="text-center">
            Need an account? <a href="{% url 'signupUser' %}">Sign Up here</a>
        </div>
    </div>
</div>

{% endblock %}

quizez/templates/quizez/main.html
{% extends 'base.html' %}
{% load static %}


{% block scripts %}

<script src="{% static 'quizez/main.js' %}" defer></script>

{% endblock scripts %}

{% block title %}

Python

{% endblock title %}



{% block content %}

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Are you ready?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="modal-body-confirm">


      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">No</button>
        <button type="button" id="start-button" class="btn btn-success">Yes</button>
      </div>
    </div>
  </div>
</div>

<div class="h1">
  Quiz List
</div>

{% for obj in quiz %}

<button class="btn btn-link modal-button" data-pk="{{obj.pk}}" data-quiz="{{obj.name}}"
  data-questions="{{obj.number_of_questions}}" data-pass="{{obj.required_score_to_pass}}" data-toggle="modal"
        data-target="#exampleModal">

  <div class="card" style="width: 21rem;">
    <div class="card-body">
      <h5 class="card-title"> {{obj.name}}</h5>
      <p class="card-text">{{obj.topic}}</p>
      <a href="#" class="btn btn-primary">Start</a>
    </div>
  </div>


</button>

{% endfor %}


{% endblock content %}

quizez/templates/quizez/quiz.html
{% extends 'base.html' %}
{% load static %}

{% block scripts %}

<script src="{% static 'quizez/quiz.js' %}" defer></script>

{% endblock scripts %}

{% block title %}

Quiz Of {{obj.name}}

{% endblock title %}


{% block content %}

<div class="row">
	<div class="col mb-3">
		<b>{{obj.name}}</b><br>
		Required score to pass <i><b>{{obj.required_score_to_pass}} %</b></i>
	</div>
</div>


<form id="form-quiz" class="mt-3 mb-3">

	{% csrf_token %}
	<div id="quiz-box">

	</div>

	<button type="submit" class="btn btn-primary mt-3">Submit</button>

</form>

<div id="score-box"></div>
<br>
<div id="result-box"></div>
<footer>
	<a class="btn btn-warning" href="{% url 'quizez:main-view' %}">Close</a>
</footer>

{% endblock content %}

quizez/templates/quizez/results.html
<h1>Results</h1>
{% block body %}
<div>
  <br>
  <table class="table">
    <thead>
      <tr>
        <th>S.No.</th>
        <th>User</th>
        <th>Score</th>
        <th>Quiz</th>
      </tr>
    </thead>
    {% for result in results %}
    <tr>
      <td>{{ forloop.counter }}</td>
      <td>{{result.user}}</td>
      <td>{{result.score}}</td>
      <td>{{result.quiz}}</td>
    </tr>
    {% endfor %}



    <tr>
      <td>{{avg}} </td>
    </tr>


  </table>
  <br>
  <button><a href="/main">close</a></button>
</div>
{% endblock %}

quizez/templates/quizez/signupuser.html
{% extends "base.html" %}

{% block content %}
<div class="row justify-content-center mt-5">
    <div class="col-md-5">
        <h2>Sign Up</h2>
    </div>
</div>
<div class="row justify-content-center mt-5">
    <div class="col-md-5">
        {% if error %}
        <div class="alert alert-danger" role="alert">
            {{ error }}
        </div>
        {% endif %}
        <form method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="username">Username</label>
                <input type="text" name="username" class="form-control" id="username" aria-describedby="usernameHelp">
                <small id="usernameHelp" class="form-text text-muted">Your username must be unique. We'll let you know
                    if someone has taken it already.</small>
            </div>
            <div class="form-group">
                <label for="password1">Password</label>
                <input type="password" name="password1" class="form-control" id="password1">
            </div>
            <div class="form-group">
                <label for="password2">Confirm Password</label>
                <input type="password" name="password2" class="form-control" id="password2">
            </div>
            <button type="submit" class="btn btn-primary">Sign Up</button>
        </form>
        <hr>
        <div class="text-center">
            Do you already have an account? <a href="{% url 'loginUser' %}">Login here</a>
        </div>
    </div>
</div>
{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">



  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- favicon -->
  <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}" />
  <link rel="stylesheet" type="text/css" href="semantic/dist/semantic.min.css">
  <script src="https://code.jquery.com/jquery-3.1.1.min.js"
    integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>
  <script src="semantic/dist/semantic.min.js"></script>
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
    integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

  <!-- jquery -->
  <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
  <!-- custom css & js-->
  <link rel="stylesheet" href="{% static 'style.css' %}">

  {% block scripts %}
  {% endblock scripts %}
  <title>Take a Quiz | {% block title %}{% endblock title %}</title>

</head>
<style>

  .container-fluid {
    height: 60px;
  }

  .head1 {
    color: #fff;
    font-size: 2rem;
    font-weight: bold;

  }

  .nav-link {
    color: white;
    font-size: 18px;
    font-family: sans-serif;
  }

  .navbar-customclass {
    background-color: #302568;
  }

</style>

<body>
  <nav class="navbar navbar-customclass navbar-expand-sm">
    <div class="container">
      <a class="navbar-brand" href="">

        <span class="head1">Django Quiz</span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        {% if user.is_authenticated %}
        <ul class="navbar-nav mr-auto">
          <li>
            <a class="nav-link" href="">Welcome {{request.user}}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/results">Results</a>
          </li>
        </ul>

        {% else %}
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="/admin">Admin Portal</a>
          </li>
        </ul>
        {% endif %}

        <ul class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a href="#" onclick="$('#signOutBtn').click()" class="nav-link">Logout</a>
            <form style='display: none;' method="POST" action="{% url 'logoutUser' %}">
              {% csrf_token %}
              <button id="signOutBtn" type="submit">Logout</button>
            </form>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'signupUser' %}">Sign Up</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'loginUser' %}">Login</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>


</body>

</body>

<div class="container mt-3">
  {% block content %}

  {% endblock content %}
</div>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
  integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
  integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
  integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
  integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
  integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</html>